membuat layout base untuk sidebar dan topbar
weboendercommunity/laravel-stockies pull request #15
Opened 2021-11-27 10:50 UTC by yal-firyal

- nambahin file base di layouts di dalamnya ada:
   @section layouts.sidebar
   @section layouts.topbar
- di file sidebar dan topbar ditambahin @yield
- di file welcome ditambahin @extends

2021-11-27 11:04 UTC, shevaathalla requested changes
ada beberapa revisi @yal-firyal 

refrensi layout base:
https://pastebin.com/A5pMsz1g

2021-11-27 11:04 UTC, shevaathalla commented on resources/views/layouts/base.blade.php
> +        @endsection
lebih enak pake `@include` si

2021-11-27 11:04 UTC, shevaathalla commented on resources/views/welcome.blade.php
>      @include('layouts.sidebar')
klo udah `@extends` gaperlu `@include`

2021-11-27 11:04 UTC, shevaathalla commented on resources/views/welcome.blade.php
> +    @endsection
ini juga kliatan aneh

2021-11-27 11:04 UTC, shevaathalla commented on resources/views/welcome.blade.php
> +                @endsection
ini juga

2021-11-27 11:04 UTC, shevaathalla commented on resources/views/welcome.blade.php
>                  @include('layouts.topbar')
dihapus aja pake extend doang

2021-11-28 08:13 UTC, yal-firyal commented on resources/views/layouts/base.blade.php
> +        @endsection
berarti pake include aja ya mas?

2021-11-28 08:43 UTC, shevaathalla commented on resources/views/layouts/base.blade.php
> +        @endsection
yapp

2021-11-28 11:30 UTC, shevaathalla reviewed
file `base.blade.php` ini kenapa kok dihapus @yal-firyal?

2021-11-29 06:18 UTC, shevaathalla reviewed
`welcome.blade.php` masih kurang, tp basenya udah lumayan bener ada penyesuaian dikit
ini aku kasih refrensi bikin welcome.blade.php pake keyword `@extends`
https://pastebin.com/Dr0vPh9P

2021-11-29 06:18 UTC, shevaathalla commented on resources/views/layouts/base.blade.php
> +                    </div>
dihapus aja gpp km panggil lagi di `welcome.blade.php`

2021-11-29 06:18 UTC, shevaathalla commented on resources/views/layouts/base.blade.php
> +    @yield('content')
hapus aja karena udah ada dibawah

2021-11-29 07:24 UTC, shevaathalla approved these changes
sipp keren akhirnyaa kelar @yal-firyal, mama kamu pasti bangga

2021-11-29 07:24 UTC, merged